'use client';

import { useState } from 'react';

type Team = { id: string; opportunityId: string; name: string; status: string; isOwner?: boolean };
type Request = { id: string; displayName: string; message: string | null; status: string };

export function TeamManager({ teams, reload }: { teams: Team[]; reload: () => Promise<void> }) {
  const [requests, setRequests] = useState<Record<string, Request[]>>({}); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  async function load(teamId: string) { try { const response = await fetch(`/api/teams/${teamId}/requests`, { cache: 'no-store' }); if (!response.ok) throw new Error(); const data = await response.json() as { items: Request[] }; setRequests((current) => ({ ...current, [teamId]: data.items })); } catch { setError('Requests could not be loaded.'); } }
  async function decide(teamId: string, requestId: string, action: 'accept' | 'reject') { setBusy(requestId); setError(null); try { const response = await fetch(`/api/teams/${teamId}/requests/${requestId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action }) }); if (!response.ok) throw new Error(); await load(teamId); await reload(); } catch { setError('Request could not be updated. Refresh and try again.'); } finally { setBusy(null); } }
  async function close(teamId: string) { if (!window.confirm('Close this team? It cannot be reopened.')) return; setBusy(teamId); try { const response = await fetch(`/api/teams/${teamId}`, { method: 'DELETE' }); if (!response.ok) throw new Error(); await reload(); } catch { setError('Team could not be closed.'); } finally { setBusy(null); } }
  async function edit(teamId: string) { const introduction = window.prompt('New introduction (leave blank to clear)'); if (introduction === null) return; const contactLink = window.prompt('New contact link (leave blank to keep the current link)'); if (contactLink === null) return; setBusy(teamId); try { const body: Record<string, string | null> = { introduction }; if (contactLink.trim()) body.contact_link = contactLink.trim(); const response = await fetch(`/api/teams/${teamId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); await reload(); } catch { setError('Team details could not be updated.'); } finally { setBusy(null); } }
  const owned = teams.filter((team) => team.isOwner);
  if (!owned.length) return null;
  return <section className="space-y-3"><h2 className="text-lg font-semibold">Manage teams</h2>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<ul className="space-y-3">{owned.map((team) => <li key={team.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{team.name} · {team.status}</span><div className="flex gap-2"><button type="button" onClick={() => void edit(team.id)} className="rounded-md border px-2 py-1 text-sm">Edit</button><button type="button" onClick={() => void load(team.id)} className="rounded-md border px-2 py-1 text-sm">View requests</button>{team.status === 'open' && <button disabled={busy === team.id} type="button" onClick={() => void close(team.id)} className="rounded-md border border-red-300 px-2 py-1 text-sm text-red-700">Close</button>}</div></div>{requests[team.id] && <ul className="mt-3 space-y-2 text-sm">{requests[team.id].length ? requests[team.id].map((request) => <li key={request.id} className="flex flex-wrap items-center justify-between gap-2 border-t pt-2"><span>{request.displayName}{request.message ? ` - ${request.message}` : ''} <em className="text-slate-500">({request.status})</em></span>{request.status === 'pending' && <span className="flex gap-1"><button disabled={busy === request.id} onClick={() => void decide(team.id, request.id, 'accept')} className="rounded-md border px-2 py-1">Accept</button><button disabled={busy === request.id} onClick={() => void decide(team.id, request.id, 'reject')} className="rounded-md border px-2 py-1">Reject</button></span>}</li>) : <li>No requests.</li>}</ul>}</li>)}</ul></section>;
}
